#!/usr/bin/env node
// dependabot-gaps 0.2.0 - generated by scripts/bundle.mjs, do not edit
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);

// src/comment-cli.ts
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

// src/comment.ts
var COMMENT_MARKER = "<!-- dependabot-gaps:sticky -->";
var MAX_COMMENT = 6e4;
function buildBody(markdown) {
  let text = markdown.trim();
  if (text.length > MAX_COMMENT) text = `${text.slice(0, MAX_COMMENT)}

_(report truncated; see the job summary for the full text)_`;
  return `${COMMENT_MARKER}
${text}
`;
}
function commentEligibility(event, repo) {
  const e = event;
  const pr = e?.pull_request;
  if (!pr || typeof pr.number !== "number") return { skip: "not a pull request event" };
  const headRepo = pr.head?.repo?.full_name;
  if (!headRepo || headRepo.toLowerCase() !== repo.toLowerCase()) return { skip: "pull request from a fork (the token is read-only there)" };
  return { pr: pr.number };
}
async function call(t, method, path, body) {
  const f = t.fetchImpl ?? fetch;
  return f(`${t.apiUrl.replace(/\/+$/, "")}${path}`, {
    method,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${t.token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "dependabot-gaps",
      ...body !== void 0 ? { "Content-Type": "application/json" } : {}
    },
    ...body !== void 0 ? { body: JSON.stringify(body) } : {}
  });
}
var denied = (status) => status === 401 || status === 403;
async function upsertComment(t, markdown) {
  const body = buildBody(markdown);
  let existing;
  for (let page = 1; page <= 10 && !existing; page++) {
    const res2 = await call(t, "GET", `/repos/${t.repo}/issues/${t.pr}/comments?per_page=100&page=${page}`);
    if (denied(res2.status)) return { action: "skipped", reason: `the token cannot read pull request comments (HTTP ${res2.status}); grant pull-requests: write` };
    if (!res2.ok) return { action: "skipped", reason: `could not list comments (HTTP ${res2.status})` };
    const items = await res2.json();
    const hit = items.find((c) => typeof c.body === "string" && c.body.startsWith(COMMENT_MARKER));
    if (hit) existing = { id: hit.id, body: hit.body };
    if (items.length < 100) break;
  }
  if (existing) {
    if (existing.body === body) return { action: "unchanged", id: existing.id };
    const res2 = await call(t, "PATCH", `/repos/${t.repo}/issues/comments/${existing.id}`, { body });
    if (denied(res2.status)) return { action: "skipped", reason: `the token cannot edit the comment (HTTP ${res2.status}); grant pull-requests: write` };
    if (!res2.ok) return { action: "skipped", reason: `could not update the comment (HTTP ${res2.status})` };
    return { action: "updated", id: existing.id };
  }
  const res = await call(t, "POST", `/repos/${t.repo}/issues/${t.pr}/comments`, { body });
  if (denied(res.status)) return { action: "skipped", reason: `the token cannot create comments (HTTP ${res.status}); grant pull-requests: write` };
  if (!res.ok) return { action: "skipped", reason: `could not create the comment (HTTP ${res.status})` };
  const created = await res.json();
  return { action: "created", id: created.id };
}

// src/comment-cli.ts
async function main(argv, env, log = (s) => process.stdout.write(`${s}
`)) {
  const file = argv[0];
  if (!file) {
    log("usage: dependabot-gaps-comment <markdown-file>");
    return 2;
  }
  const repo = env.GITHUB_REPOSITORY;
  const token = env.GITHUB_TOKEN;
  if (!repo || !token || !env.GITHUB_EVENT_PATH) {
    log("::notice::dependabot-gaps: no sticky comment (GITHUB_REPOSITORY, GITHUB_TOKEN or GITHUB_EVENT_PATH missing)");
    return 0;
  }
  const verdict = commentEligibility(JSON.parse(readFileSync(env.GITHUB_EVENT_PATH, "utf8")), repo);
  if ("skip" in verdict) {
    log(`::notice::dependabot-gaps: no sticky comment (${verdict.skip})`);
    return 0;
  }
  try {
    const out = await upsertComment({ apiUrl: env.GITHUB_API_URL ?? "https://api.github.com", token, repo, pr: verdict.pr }, readFileSync(file, "utf8"));
    log(out.action === "skipped" ? `::warning::dependabot-gaps: sticky comment skipped: ${out.reason}` : `dependabot-gaps: sticky comment ${out.action} (#${out.id})`);
  } catch (err) {
    log(`::warning::dependabot-gaps: sticky comment failed: ${err.message}`);
  }
  return 0;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2), process.env).then((c) => {
    process.exitCode = c;
  });
}
export {
  main
};
